easy_admin:
    entities:
        Taille:
              class: App\Entity\Taille
              form:
                  fields: [libelle, short]
        Produit:
              class: App\Entity\Produit
              form:
                fields:
                  - 'libelle'
                  - 'quantite'
                  - 'prix'
                  - 'taille'
                  - 'couleur'
                  - 'image'
                  - 'produitType'
        Commande:
          class: App\Entity\Commande
        User:
          class: App\Entity\User
        Couleurs:
          class: App\Entity\Couleurs
          form:
            fields:
              - 'libelle'
        ProduitType:
          class: App\Entity\ProduitType
          form:
            fields:
              - 'libelle'